image: node:alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm

stages:
  - test
  - build
  - deploy

before_script:
  - npm ci --cache .npm
  - apk add --no-cache bash git

eas-build:
  stage: build
  tags:
    - docker
  script:
    # Note: there is a limit of 30 EAS builds per month:
    - echo "npx eas-cli build --platform all --profile preview --non-interactive"

web-build:
  stage: build
  tags:
    - docker
  script:
    - npx expo export:web
  artifacts:
    paths:
      - web-build/

unit-test-job:
  stage: test
  tags:
    - docker
  script:
    - npm run test
  allow_failure: true

lint-test-job:
  stage: test
  tags:
    - docker
  script:
    - npx eslint .
  allow_failure: true

web-deploy:
  stage: deploy
  tags:
    - docker
  environment:
    name: production
    url: https://smartalarm.netlify.app/
  script:
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --dir=web-build/
