image: node:alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm

stages:
  - test
  - build
  - deploy

before_script:
  - npm ci --cache .npm

eas-build:
  stage: build
  tags:
    - docker
  script:
    - apk add --no-cache bash git
    # Note: there is a limit of 30 EAS builds per month:
    - npx eas-cli build --platform all --profile preview --non-interactive

web-build:
  stage: build
  tags:
    - docker
  script:
    - apk add --no-cache bash git
    - npx expo export:web
  artifacts:
    paths:
      - web-build/

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests... It should take 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"

lint-test-job:
  stage: test
  script:
    - echo "Linting code... It should take 10 seconds."
    - sleep 10
    - echo "No lint issues found."

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."